services:
  - type: web
    name: telegram-bot-worker
    env: python
    plan: starter
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GROUP_CHAT_ID
        sync: false
      - key: GOOGLE_CREDS_JSON
        sync: false
    autoDeploy: false
